### ISSUE TITLE
How to structure geojson?

### ISSUE THREAD

**Issue by rowanwins** [substack/earth-mesh#1]
Gday,

Thanks for what looks like a useful library! 

Im just wondering how you structure your geojson, in particular where are you expecting the z value to be?

Im presuming I can pass in a standard geojson `featurecollection` with a bunch of points, do the z values get stored as the 3rd item in the coordinates array? Or perhaps as a property?

Any tips would be appreciated!

Thanks,
Rowan

**Comment by substack** [comment]
You don't need to set a z value, but you could use one for elevation. The z value on the result is used for things like an ecef (3d xyz) projection. There were some changes since v1 so maybe I missed some parts of the updated docs.
